/*
 * Generated by Bluespec Compiler, version 2014.03.beta2 (build 33633, 2014-03-26)
 * 
 * On Tue Sep  9 02:14:35 EDT 2014
 * 
 * To automatically register this VPI wrapper with a Verilog simulator use:
 *     #include "vpi_wrapper_get_tlp.h"
 *     void (*vlog_startup_routines[])() = { get_tlp_vpi_register, 0u };
 * 
 * For a Verilog simulator which requires a .tab file, use the following entry:
 * $imported_get_tlp call=get_tlp_calltf size=153 acc=rw:%TASK
 * 
 * For a Verilog simulator which requires a .sft file, use the following entry:
 * $imported_get_tlp vpiSysFuncSized 153 unsigned
 */
#include <stdlib.h>
#include <vpi_user.h>
#include "bdpi.h"

/* the type of the wrapped function */
void get_tlp(unsigned int *);

/* VPI wrapper function */
PLI_INT32 get_tlp_calltf(PLI_BYTE8 *user_data)
{
  vpiHandle hCall;
  unsigned int *vpi_result;
  vpiHandle *handle_array;
  
  /* retrieve handle array */
  hCall = vpi_handle(vpiSysTfCall, 0);
  handle_array = vpi_get_userdata(hCall);
  if (handle_array == NULL)
  {
    vpiHandle hArgList;
    hArgList = vpi_iterate(vpiArgument, hCall);
    handle_array = malloc(sizeof(vpiHandle) * 1u);
    handle_array[0u] = hCall;
    vpi_put_userdata(hCall, handle_array);
    vpi_free_object(hArgList);
  }
  
  /* create return value */
  make_vpi_result(handle_array[0u], &vpi_result, DIRECT);
  
  /* call the imported C function */
  get_tlp(vpi_result);
  
  /* copy out return value */
  put_vpi_result(handle_array[0u], &vpi_result, DIRECT);
  vpi_free_object(hCall);
  
  return 0;
}

/* sft: $imported_get_tlp vpiSysFuncSized 153 unsigned */

/* tab: $imported_get_tlp call=get_tlp_calltf size=153 acc=rw:%TASK */

PLI_INT32 get_tlp_sizetf(PLI_BYTE8 *user_data)
{
  return 153u;
}

/* VPI wrapper registration function */
void get_tlp_vpi_register()
{
  s_vpi_systf_data tf_data;
  
  /* Fill in registration data */
  tf_data.type = vpiSysFunc;
  tf_data.sysfunctype = vpiSizedFunc;
  tf_data.tfname = "$imported_get_tlp";
  tf_data.calltf = get_tlp_calltf;
  tf_data.compiletf = 0u;
  tf_data.sizetf = get_tlp_sizetf;
  tf_data.user_data = "$imported_get_tlp";
  
  /* Register the function with VPI */
  vpi_register_systf(&tf_data);
}
