/*
 * Generated by Bluespec Compiler, version 2014.03.beta2 (build 33633, 2014-03-26)
 * 
 * On Tue Sep  9 02:14:35 EDT 2014
 * 
 */
#ifndef __vpi_wrapper_can_put_tlp_h__
#define __vpi_wrapper_can_put_tlp_h__

#include <vpi_user.h>

/* registration function */
void can_put_tlp_vpi_register();

/* VPI wrapper function */
PLI_INT32 can_put_tlp_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_can_put_tlp_h__ */
