flashemul: BLUEDBM_PLATFORMDIR=../src/bluedbm_platform/test_platform/
flashemul: BSVFILES = Interface.bsv Top.bsv 
flashemul: BSVFILES_ALL = $(BSVFILES) $(BLUEDBM_PLATFORMDIR)/BlueDBMPlatform.bsv 
flashemul: XBSVFLAGS=--verilog ../../../xbsv/xilinx/ddr3_v1_7/ --constraint ../../xbsv/xilinx/constraints/vc707_ddr3.xdc --clib rt


