emultest: BLUEDBM_PLATFORMDIR=../src/bluedbm_platform/test_platform/
emultest: BLUEDBM_FLASHDIR=../src/hardware_controller/flash/emulated/
emultest: BLUEDBM_DRAMDIR=../src/hardware_controller/dram/raw_64/

emultest: BSVFILES = Interface.bsv Top.bsv 
emultest: BSVFILES_ALL = $(BSVFILES) $(BLUEDBM_PLATFORMDIR)/BlueDBMPlatform.bsv \
	$(BLUEDBM_PLATFORMDIR)/PlatformInterfaces.bsv \
	$(BLUEDBM_FLASHDIR)/EmulatedFlash.bsv \
	$(BLUEDBM_DRAMDIR)/DRAMController.bsv
emultest: XBSVFLAGS=--verilog ../../../xbsv/xilinx/ddr3_v1_7/ \
	--verilog ../../../xbsv/xilinx/aurora_64b66b_v7/ \
	--constraint ../../xbsv/xilinx/constraints/vc707_aurora.xdc \
	--constraint ../../xbsv/xilinx/constraints/vc707_ddr3.xdc \
	--xci ../../../xbsv/xilinx/aurora_64b66b_v7/aurora_64b66b_0.xci \
	--clib rt
emultest: CPPFILES_ALL = $(CPPFILES) $(BLUEDBM_PLATFORMDIR)/platform.cpp


# import_ip -files {/home/wjun/bluedbm_work/xbsv/xilinx/aurora_64b66b_v7/aurora_64b66b_0.xci} -name aurora_64b66b_0
